Add new target for uploading binaries to release
cloudposse/build-harness pull request #83
Opened 2018-07-25 12:10 UTC by vadim-hleif

### what
* Add new `github/push-artifacts` target

### why
* For uploading artifacts in a codefresh build step

2018-07-25 17:40 UTC, osterman commented on bin/github_push_artifacts.sh
> +ghr -t $GITGUB_TOKEN $TAG $ARTIFACTS
I don't see any benefit with having a shell script here. Use shell scripts when there is complicated bash logic/flow control.  Use inline commands in make targets when there's just a one-liner.

2018-07-25 17:41 UTC, osterman commented
This PR should be depended on another one in packages.

2018-07-25 17:42 UTC, osterman requested changes
See inline comments

2018-07-26 17:45 UTC, osterman commented on modules/github/Makefile.release
> +
Add a target description. e.g.
```
## Push all release artifacts to GitHub
```

2018-07-26 17:46 UTC, osterman commented on modules/github/Makefile.release
> +github/push-artifacts:
Add a package dependency here:

```
github/push-artifacts: packages/install/ghr
```

2018-07-30 06:28 UTC, osterman commented on modules/github/Makefile.release
> +	@ghr -t $(GITHUB_TOKEN) $(GIT_TAG) $(ARTIFACTS)
Can `ghr` work without passing the token as a parameter? E.g. can it look in the environment? Would rather not pass it on the command line if we can avoid it.

2018-07-30 06:28 UTC, osterman reviewed
See inline comments

2018-07-30 06:30 UTC, goruha requested changes
Update package version to use https://github.com/cloudposse/packages/pull/27

2018-07-30 18:44 UTC, osterman requested changes
See comment by @goruha

2018-08-02 13:36 UTC, vadim-hleif commented
#### Depend on 
- https://github.com/cloudposse/packages/pull/27

2018-08-02 19:38 UTC, osterman commented on modules/github/Makefile.release
> +## To use ghr, you need a GitHub API token.
Target annotations `##` must be on one-line and cannot repeat. Also, they must immediately precede the target name. This is due to how it's implemented with `awk`: https://github.com/cloudposse/build-harness/blob/master/Makefile.helpers#L39-L51

Instead, notes to developers should just use a single `#`. See other examples in makefiles.

2018-08-02 19:39 UTC, osterman commented on modules/github/Makefile.release
> +## Push all release artifacts to GitHub
Perhaps write: 
```
## Push all release artifacts to GitHub (Required: GITHUB_TOKEN)
```

2018-08-02 19:39 UTC, osterman requested changes
See inline comments

2018-08-07 16:35 UTC, goruha approved these changes

2018-08-07 23:23 UTC, osterman approved these changes

2018-08-08 08:46 UTC, merged

2018-08-13 17:09 UTC, osterman commented
https://github.com/cloudposse/build-harness/issues/82